name: Plugin Update
'on':
  push:
    branches:
      - plugin/*
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - run: python ./.github/scripts/append_plugin.py
      - run: ./.github/scripts/commit_push.sh
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DEPLOY_TOKEN: '${{ secrets.DEPLOY_TOKEN }}'
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref_name }} into main"
          pr_body: "👑 *An automated PR*"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}